Repository Team-Umbba/Umbba-Android, pull requests merged in 2023-09, with the labels that each got.

#117 [Feat/#116] 문답화면 로딩뷰 추가
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_question_answer.xml
Labels: feature, 서현

#119 [Chore/#118] 디테일 변경
  app/src/main/java/com/ubcompany/umbba_android/presentation/onboarding/SetTimeActivity.kt
  app/src/main/res/drawable-hdpi/img_communication.png
  app/src/main/res/drawable-mdpi/img_communication.png
  app/src/main/res/drawable-xhdpi/img_communication.png
  app/src/main/res/drawable-xxhdpi/img_communication.png
  app/src/main/res/drawable-xxxhdpi/img_communication.png
  app/src/main/res/layout/activity_communication.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_onboarding_finish.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: chore, fix, 연진

#121 [Chore/#120] 링크,로딩뷰 수정
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: chore

#123 [Feat/#122] 카카오 토큰 삭제 기능 추가
  app/src/main/java/com/ubcompany/umbba_android/presentation/login/LoginActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/setting/DeleteAccountDialogFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/setting/ManageAccountActivity.kt
Labels: feature, 연진

#125 [Fix/#124] 자동로그인 관련 오류 수정 및 문구 변경
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: chore, fix, 연진
