Repository Team-Umbba/Umbba-Android, pull requests merged in 2023-10, with the labels that each got.

#132 [Feat/#130] 업데이트 팝업 구현
  app/build.gradle
  app/src/main/java/com/ubcompany/umbba_android/data/local/SharedPreferences.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/UpdateDialogFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/fragment_update_dialog.xml
  app/src/main/res/values/strings.xml
Labels: feature, fix, 서현

#133 [Fix/#129] 메세지에 들어가는 동적링크 수정
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/InviteCodeDialogFragment.kt
  app/src/main/res/values/strings.xml
Labels: fix, 연진

#135 [Fix/#134] 동적링크 오류 해결
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/InviteCodeDialogFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/invite/InviteCodeActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/login/LoginActivity.kt
Labels: fix, 연진

#139 [Design/#136] 교신화면 고도화
  app/src/main/java/com/ubcompany/umbba_android/presentation/onboarding/CommunicationActivity.kt
  app/src/main/res/anim/fadeout_short.xml
  app/src/main/res/drawable-hdpi/img_communication.png
  app/src/main/res/drawable-mdpi/img_communication.png
  app/src/main/res/drawable-xhdpi/img_communication.png
  app/src/main/res/drawable-xxhdpi/img_communication.png
  app/src/main/res/drawable-xxxhdpi/img_communication.png
  app/src/main/res/layout/activity_communication.xml
  app/src/main/res/raw/communication.gif
Labels: design, 연진

#141 [Fix/#140] iOS 파라미터 추가
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/InviteCodeDialogFragment.kt
Labels: fix
