Repository Team-Umbba/Umbba-Android, pull requests merged in 2023-07, with the labels that each got.

#2 [Design/#1] 초대코드 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/MainActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InviteCodeActivity.kt
  app/src/main/res/color/sel_invite_code_input_layout.xml
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/sel_invite_code_btn_next.xml
  app/src/main/res/drawable/shape_black_fill_r50_rect.xml
  app/src/main/res/drawable/shape_g300_fill_r50_rect.xml
  app/src/main/res/font/cafe24_classic_type.ttf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/font/umbba_font.xml
  app/src/main/res/layout/activity_invite_code.xml
  app/src/main/res/layout/basic_appbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: design, 서현

#6 [Design/#3] 정보 입력 화면 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SelectFamilyActivity.kt
  app/src/main/res/color/sel_choice_chip_color.xml
  app/src/main/res/color/sel_choice_chip_stroke.xml
  app/src/main/res/color/sel_choice_chip_text.xml
  app/src/main/res/drawable/shape_grey_stroke_r8_rect.xml
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_select_family.xml
  app/src/main/res/layout/basic_appbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: design, 연진

#8 [Design/#7] 로그인, 시작하기 화면 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InviteActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/LoginActivity.kt
  app/src/main/res/drawable/shape_grey_btn_r50_rectangle.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
Labels: design, 연진

#13 [Design/#12] 답변 화면 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/MainActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/AnswerActivity.kt
  app/src/main/res/color/sel_answer_input_layout.xml
  app/src/main/res/color/sel_invite_code_input_layout.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/shape_grey_appbar_r68_rect.xml
  app/src/main/res/drawable/shape_grey_fill_r17_rect.xml
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_invite_code.xml
  app/src/main/res/layout/activity_notify_time.xml
  app/src/main/res/layout/basic_appbar.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/qna_appbar.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: design, 서현

#15 [Design/#9] 시간 설정 화면 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SetTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/util/CustomTimePickerInterval.kt
  app/src/main/res/layout/activity_set_time.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, design, 연진

#16 [Design/#14] 문답 화면 UI 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/MainActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/QuestionAnswerActivity.kt
  app/src/main/res/color/sel_answer_input_layout.xml
  app/src/main/res/drawable/shape_grey_appbar_r68_rect.xml
  app/src/main/res/drawable/shape_grey_fill_r17_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: feature, design, 서현

#18 [Chore/#17] 폴더링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/presentation/MainActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteCodeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
Labels: chore, 연진

#21 [Design/#19] 홈 화면 UI 구현
  app/src/main/java/com/sopt/umbba_android/presentation/MainActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/res/drawable/iv_maru.jpg
  app/src/main/res/drawable/shape_grey_fill_r84_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/layout/activity_set_time.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: design, 서현

#23 [Design/#20] 메인 뷰 다이얼로그 화면 UI 구현
  app/src/main/java/com/sopt/umbba_android/presentation/home/InviteCodeDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ConfirmAnswerDialogFragment.kt
  app/src/main/res/drawable/ic_close_black.xml
  app/src/main/res/drawable/inset_dialog_background.xml
  app/src/main/res/drawable/shape_grey74_btn_r50_rect.xml
  app/src/main/res/drawable/shape_grey_btn_r50_stroke_rect.xml
  app/src/main/res/drawable/shape_grey_dialog_r16_rect.xml
  app/src/main/res/drawable/shape_grey_line_3dp_rect.xml
  app/src/main/res/layout/fragment_confirm_answer_dialog.xml
  app/src/main/res/layout/fragment_invite_code_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design, 연진

#28 [Design/#25] 리스트 화면 UI 구현
  app/src/main/java/com/sopt/umbba_android/presentation/MainActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/list/ListFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/list/ListQuestionAdapter.kt
  app/src/main/res/color/sel_choice_chip_color.xml
  app/src/main/res/color/sel_quest_choice_chip_text.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/item_question_list.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: design, 연진

#36 [Design/#29] Color System 및 바뀐 placeHolder 적용
  app/src/main/res/color/sel_answer_input_layout.xml
  app/src/main/res/color/sel_btn_pri500_text.xml
  app/src/main/res/color/sel_choice_chip_pri500_color.xml
  app/src/main/res/color/sel_choice_chip_pri500_stroke.xml
  app/src/main/res/color/sel_choice_chip_pri500_text.xml
  app/src/main/res/color/sel_choice_chip_pri600_color.xml
  app/src/main/res/color/sel_choice_chip_pri600_text.xml
  app/src/main/res/color/sel_choice_chip_stroke.xml
  app/src/main/res/color/sel_choice_chip_text.xml
  app/src/main/res/color/sel_invite_code_input_layout.xml
  app/src/main/res/drawable/ic_kakao_talk_logo.xml
  app/src/main/res/drawable/ic_umbba_logo.xml
  app/src/main/res/drawable/ic_umbba_logo_big.xml
  app/src/main/res/drawable/inset_dialog_background.xml
  app/src/main/res/drawable/progress_bar_quest.xml
  app/src/main/res/drawable/sel_btn_answer.xml
  app/src/main/res/drawable/sel_btn_next.xml
  app/src/main/res/drawable/shape_g300_fill_r50_rect.xml
  app/src/main/res/drawable/shape_g400_btn_r50_rect.xml
  app/src/main/res/drawable/shape_g400_stroke_r8_rect.xml
  app/src/main/res/drawable/shape_gradient_btn_r50_rect.xml
  app/src/main/res/drawable/shape_grey_btn_r50_stroke_rect.xml
  app/src/main/res/drawable/shape_grey_fill_r17_rect.xml
  app/src/main/res/drawable/shape_grey_fill_r84_rect.xml
  app/src/main/res/drawable/shape_grey_line_3dp_rect.xml
  app/src/main/res/drawable/shape_pri500_appbar_r68_rect.xml
  app/src/main/res/drawable/shape_pri500_btn_r50_rect.xml
  app/src/main/res/drawable/shape_pri500_btn_stroke_r50_rect.xml
  app/src/main/res/drawable/shape_pri500_stroke_r56_rect.xml
  app/src/main/res/drawable/shape_pri600_r84_rect.xml
  app/src/main/res/drawable/shape_white_dialog_r16_rect.xml
  app/src/main/res/drawable/shape_yellow_btn_r50_rect.xml
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_invite_code.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_notify_time.xml
  app/src/main/res/layout/activity_quest.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/layout/activity_select_family.xml
  app/src/main/res/layout/activity_set_time.xml
  app/src/main/res/layout/basic_appbar.xml
  app/src/main/res/layout/fragment_back_answer_dialog.xml
  app/src/main/res/layout/fragment_confirm_answer_dialog.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_invite_code_dialog.xml
  app/src/main/res/layout/fragment_quest_one.xml
  app/src/main/res/layout/qna_appbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: delete, design, 연진

#38 [Feat/#35] 화면 전환 로직붙이기
  app/src/main/java/com/sopt/umbba_android/presentation/BasicAppbarFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteCodeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/NotifyTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/QuestActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SelectFamilyActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SetTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/DeleteAccountActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/ManageAccountActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
  app/src/main/res/color/sel_btn_pri500_text.xml
  app/src/main/res/drawable/sel_btn_answer.xml
  app/src/main/res/drawable/shape_switch_thumb.xml
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_delete_account.xml
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_invite_code.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_manage_account.xml
  app/src/main/res/layout/activity_notify_time.xml
  app/src/main/res/layout/activity_quest.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/layout/activity_select_family.xml
  app/src/main/res/layout/activity_set_time.xml
  app/src/main/res/layout/basic_appbar.xml
  app/src/main/res/layout/fragment_back_answer_dialog.xml
  app/src/main/res/layout/fragment_invite_code_dialog.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_question_list.xml
  app/src/main/res/layout/qna_appbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feature, 서현

#42 [Design/#39] 설정 switch 커스텀
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_setting.xml
Labels: design, 서현

#41 [Feat/#40] 설정 노션연결
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
Labels: feature, 서현

#48 [Feat/#46] 화면 연결 및 버튼 활성화
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/AgreePrivacyUseActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/CommunicationActivity.kt
  app/src/main/res/color/sel_btn_pri500_text.xml
  app/src/main/res/color/sel_btn_white_text.xml
  app/src/main/res/drawable/sel_btn_agree.xml
  app/src/main/res/drawable/sel_btn_agree_circle.xml
  app/src/main/res/layout/activity_agree_privacy_use.xml
  app/src/main/res/layout/activity_communication.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/values/strings.xml
Labels: feature, design, 연진

#52 [Feat/#51] FCM Service 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
  app/src/main/java/com/sopt/umbba_android/util/fcm/MyFirebaseMessagingService.kt
  build.gradle
Labels: feature, 서현

#58 [Feat/#49] 초대하는 측 정보 입력 화면 연결 및 분기처리
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SelectFamilyActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SetTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/splash/OnboardingActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/viewmodel/InputInfoViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/viewmodel/SelectFamilyViewModel.kt
  app/src/main/res/drawable/ic_close_grey.xml
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_select_family.xml
  app/src/main/res/layout/fragment_back_answer_dialog.xml
  app/src/main/res/layout/fragment_confirm_answer_dialog.xml
  app/src/main/res/raw/splash_logo.gif
  app/src/main/res/values/styles.xml
Labels: feature, 연진

#56 [Feat/#53] 설정 화면 MVVM 설계
  app/src/main/java/com/sopt/umbba_android/data/datasource/SettingRemoteDataSource.kt
  app/src/main/java/com/sopt/umbba_android/data/model/ApiFactory.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/SettingRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/service/SettingService.kt
  app/src/main/java/com/sopt/umbba_android/domain/repository/SettingRepository.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/DeleteAccountDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/DeleteAccountViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/ManageAccountActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/ManageAccountViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
Labels: feature, 서현

#60 [Feat/#57] 문답화면 API 연결
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/data/datasource/QuestionAnswerRemoteDataSource.kt
  app/src/main/java/com/sopt/umbba_android/data/model/ApiFactory.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/QuestionAnswerResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/QuestionAnswerRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/service/QuestionAnswerService.kt
  app/src/main/java/com/sopt/umbba_android/domain/repository/QuestionAnswerRepository.kt
  app/src/main/java/com/sopt/umbba_android/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SelectFamilyActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SelectFamilyViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/NoOpponentDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ViewModelFactory.kt
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/layout/activity_select_family.xml
  app/src/main/res/layout/fragment_no_opponent_dialog.xml
  app/src/main/res/values/strings.xml
Labels: feature, 서현

#62 [Feat/#59] 푸시 알림 권한 허용
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteCodeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/viewmodel/InviteCodeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/NotifyTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SetTimeActivity.kt
  app/src/main/res/drawable/img_communication.png
  app/src/main/res/layout/activity_communication.xml
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_invite_code.xml
Labels: feature, 연진

#64 [Feat/#61] 홈화면 API 연결, 배경 적용
  app/src/main/java/com/sopt/umbba_android/data/datasource/HomeRemoteDataSource.kt
  app/src/main/java/com/sopt/umbba_android/data/datasource/QuestionAnswerRemoteDataSource.kt
  app/src/main/java/com/sopt/umbba_android/data/model/ApiFactory.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/HomeResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/QuestionAnswerRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/service/HomeService.kt
  app/src/main/java/com/sopt/umbba_android/data/service/QuestionAnswerService.kt
  app/src/main/java/com/sopt/umbba_android/domain/repository/HomeRepository.kt
  app/src/main/java/com/sopt/umbba_android/domain/repository/QuestionAnswerRepository.kt
  app/src/main/java/com/sopt/umbba_android/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ConfirmAnswerDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerViewModel.kt
  app/src/main/java/com/sopt/umbba_android/util/ViewModelFactory.kt
  app/src/main/res/drawable/bg_home1.png
  app/src/main/res/drawable/bg_home2.png
  app/src/main/res/drawable/bg_home3.png
  app/src/main/res/drawable/bg_home4.png
  app/src/main/res/drawable/bg_home5.png
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/layout/fragment_back_answer_dialog.xml
  app/src/main/res/layout/fragment_confirm_answer_dialog.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: feature, 서현

#69 [Feat/#63] 메인-문답-답변 API 연결
  app/src/main/java/com/sopt/umbba_android/data/datasource/HomeRemoteDataSource.kt
  app/src/main/java/com/sopt/umbba_android/data/datasource/QuestionAnswerRemoteDataSource.kt
  app/src/main/java/com/sopt/umbba_android/data/model/request/AnswerRequestDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/AnswerResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/HomeCaseResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/HomeResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/QuestionAnswerResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/QuestionAnswerRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/service/HomeService.kt
  app/src/main/java/com/sopt/umbba_android/domain/repository/HomeRepository.kt
  app/src/main/java/com/sopt/umbba_android/domain/repository/QuestionAnswerRepository.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/InviteCodeDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/viewmodel/InviteCodeDialogFragmentViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ConfirmAnswerDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ConfirmAnswerDialogFragmentViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/ConfirmAnswerDialogFragmentViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/QuestionAnswerViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/DeleteAccountDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/ManageAccountActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/viewmodel/DeleteAccountViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/viewmodel/ManageAccountViewModel.kt
  app/src/main/java/com/sopt/umbba_android/util/ViewModelFactory.kt
  app/src/main/res/drawable/ic_no_opponenet.xml
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/layout/fragment_confirm_answer_dialog.xml
  app/src/main/res/layout/fragment_invite_code_dialog.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/fragment_no_opponent_dialog.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_question_list.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature, 서현

#78 [Feat/#72] 카카오 로그인 프로젝트 세팅 및 API 연결
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/application/UmbbaApplication.kt
  app/src/main/java/com/sopt/umbba_android/data/datasource/LoginRemoteDataSource.kt
  app/src/main/java/com/sopt/umbba_android/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/umbba_android/data/local/SharedPreferences.kt
  app/src/main/java/com/sopt/umbba_android/data/model/ApiFactory.kt
  app/src/main/java/com/sopt/umbba_android/data/model/request/LoginRequestDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/LoginResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/service/LoginService.kt
  app/src/main/java/com/sopt/umbba_android/domain/repository/LoginRepository.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/sopt/umbba_android/util/ViewModelFactory.kt
  app/src/main/res/drawable/img_login.png
  app/src/main/res/drawable/img_start.png
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_login.xml
  settings.gradle
Labels: feature, 연진

#81 [Feat/#74] 알림설정 페이지 기능 구현
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
  app/src/main/java/com/sopt/umbba_android/util/fcm/MyFirebaseMessagingService.kt
Labels: feature, 서현

#84 [Feat/#75] 회원탈퇴 API 연결, 답변 확인 로직 수정
  app/src/main/java/com/sopt/umbba_android/data/local/SharedPreferences.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ConfirmAnswerDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/ConfirmAnswerDialogFragmentViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/DeleteAccountActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/DeleteAccountDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/ManageAccountActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/viewmodel/DeleteAccountViewModel.kt
  app/src/main/java/com/sopt/umbba_android/util/ViewModelFactory.kt
  app/src/main/java/com/sopt/umbba_android/util/fcm/MyFirebaseMessagingService.kt
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/strings.xml
Labels: feature, fix, design, 서현

#86 [Feat/#85] 답변, 리스트 수정사항
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/res/drawable/bg_list_img1.jpg
  app/src/main/res/drawable/bg_list_img2.jpg
  app/src/main/res/drawable/bg_list_img3.png
  app/src/main/res/drawable/bg_list_img4.jpg
  app/src/main/res/drawable/bg_list_img4.png
  app/src/main/res/drawable/bg_list_img5.jpg
  app/src/main/res/drawable/bg_list_img5.png
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/fragment_confirm_answer_dialog.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/values/strings.xml
Labels: feature, delete, design, 서현

#87 [Feat/#82] 초대하는 측 / 초대받는 측 분기처리
  app/src/main/java/com/sopt/umbba_android/domain/entity/User.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteCodeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/CommunicationActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/NotifyTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SelectFamilyActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SetTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/quest/QuestActivity.kt
  app/src/main/res/layout/activity_onboarding_finish.xml
  app/src/main/res/layout/fragment_quest_five.xml
  app/src/main/res/layout/fragment_quest_four.xml
  app/src/main/res/layout/fragment_quest_one.xml
  app/src/main/res/layout/fragment_quest_three.xml
  app/src/main/res/layout/fragment_quest_two.xml
  app/src/main/res/values/strings.xml
Labels: feature, 연진

#90 [Feat/#89] 데이터 set 과정 데이터바인딩 적용
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ConfirmAnswerDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/ConfirmAnswerDialogFragmentViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/QuestionAnswerViewModel.kt
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/layout/fragment_confirm_answer_dialog.xml
  app/src/main/res/layout/fragment_home.xml
Labels: refactor, 서현

#91 [Feat/#88] 초대하는 측 / 초대받는 측 정보 POST API 연결
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/data/datasource/OnboardingRemoteDataSource.kt
  app/src/main/java/com/sopt/umbba_android/data/local/SharedPreferences.kt
  app/src/main/java/com/sopt/umbba_android/data/model/request/ReceiveInfoRequestDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/request/SendInfoRequestDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/LoginResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/ReceiveInfoResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/SendInfoResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/OnboardingRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/service/OnBoardingService.kt
  app/src/main/java/com/sopt/umbba_android/data/service/OnboardingService.kt
  app/src/main/java/com/sopt/umbba_android/domain/repository/OnboardingRepository.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteCodeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/NotifyTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/OnboardingFinishActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SetTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/quest/QuestActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/quest/QuestViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/viewmodel/SetTimeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/splash/SplashActivity.kt
  app/src/main/java/com/sopt/umbba_android/util/ViewModelFactory.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, 연진

#93 [Feat/#92] 카카오톡 공유 메세지 커스텀
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/data/model/response/InviteCodeResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/InviteCodeDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/splash/SplashActivity.kt
Labels: feature, fix, 연진, 서현

#96 [Fix/#95] 답변, 설정 QA 반영
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/viewmodel/InviteCodeDialogFragmentViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteCodeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/list/ListQuestionAdapter.kt
  app/src/main/java/com/sopt/umbba_android/presentation/list/viewmodel/ListViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SelectFamilyActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ConfirmAnswerDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/ConfirmAnswerDialogFragmentViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/QuestionAnswerViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/viewmodel/DeleteAccountViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/viewmodel/ManageAccountViewModel.kt
  app/src/main/java/com/sopt/umbba_android/util/fcm/MyFirebaseMessagingService.kt
  app/src/main/res/layout/activity_delete_account.xml
  app/src/main/res/values/strings.xml
Labels: fix, 서현

#97 [Fix/#94] 온보딩 화면 QA 반영
  app/src/main/java/com/sopt/umbba_android/presentation/home/InviteCodeDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/NotifyTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/OnboardingFinishActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SetTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/quest/QuestActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/quest/QuestViewModel.kt
  app/src/main/res/layout/activity_notify_time.xml
Labels: fix, 연진

#99 [Chore/#98] String 추출, 로그 정리, 버그 수정
  app/src/main/java/com/sopt/umbba_android/application/UmbbaApplication.kt
  app/src/main/java/com/sopt/umbba_android/data/datasource/ExampleDateSource.kt
  app/src/main/java/com/sopt/umbba_android/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/umbba_android/data/local/SharedPreferences.kt
  app/src/main/java/com/sopt/umbba_android/data/model/request/ExampleRequestDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/ExampleResponseDto.kt
  app/src/main/java/com/sopt/umbba_android/data/model/response/wrapper/BaseResponse.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/ExampleRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/ListRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/OnboardingRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/QuestionAnswerRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/repository/SettingRepositoryImpl.kt
  app/src/main/java/com/sopt/umbba_android/data/service/ExampleService.kt
  app/src/main/java/com/sopt/umbba_android/domain/repository/ExampleRepository.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/InviteCodeDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/InviteCodeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/invite/viewmodel/InviteCodeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/list/ListFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/list/ListQuestionAdapter.kt
  app/src/main/java/com/sopt/umbba_android/presentation/list/viewmodel/ListViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/AgreePrivacyUseActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/CommunicationActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/NotifyTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/OnboardingFinishActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SelectFamilyActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SetTimeActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/quest/QuestActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/quest/QuestViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/viewmodel/SetTimeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/BackAnswerDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ConfirmAnswerDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/NoOpponentDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/ConfirmAnswerDialogFragmentViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/QuestionAnswerViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/DeleteAccountActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/DeleteAccountDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/ManageAccountActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/SettingFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/viewmodel/DeleteAccountViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/setting/viewmodel/ManageAccountViewModel.kt
  app/src/main/java/com/sopt/umbba_android/util/BasicAppbar.kt
  app/src/main/java/com/sopt/umbba_android/util/ViewExtension.kt
  app/src/main/res/layout/activity_delete_account.xml
  app/src/main/res/values/strings.xml
Labels: chore, delete, fix, 연진
