Repository Team-Umbba/Umbba-Android, pull requests merged in 2023-08, with the labels that each got.

#104 [Feat/#102] must QA 반영
  app/src/main/java/com/sopt/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/res/layout/activity_delete_account.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/values/strings.xml
Labels: feature, fix, design, 서현

#105 [Fix/#103] 온보딩 시간 설정 오류 수정
  app/src/main/java/com/sopt/umbba_android/presentation/home/InviteCodeDialogFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/SetTimeActivity.kt
Labels: fix, 연진

#108 [Feat/#107] 홈 화면 로딩뷰 추가
  app/src/main/java/com/sopt/umbba_android/presentation/MainActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/list/ListFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/ConfirmAnswerDialogFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_invite_code_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, refactor, design, 서현

#110 [Fix/#106] 자체 QA 후 발견된 오류 수정
  app/src/main/java/com/sopt/umbba_android/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/InputInfoActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/onboarding/quest/QuestActivity.kt
  app/src/main/java/com/sopt/umbba_android/util/HideKeyboard.kt
  app/src/main/res/values/strings.xml
Labels: feature, fix, 연진

#112 [Feat/#109] 엔딩페이지 구현 & 답변화면 UT 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/umbba_android/presentation/MainActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/EndingActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/umbba_android/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/AnswerActivity.kt
  app/src/main/java/com/sopt/umbba_android/presentation/qna/viewmodel/AnswerViewModel.kt
  app/src/main/res/drawable/bg_ending.png
  app/src/main/res/drawable/bg_ending_gradient.xml
  app/src/main/res/drawable/shape_g800_dot_stroke_rect.xml
  app/src/main/res/layout/activity_agree_privacy_use.xml
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_communication.xml
  app/src/main/res/layout/activity_ending.xml
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_question_answer.xml
  app/src/main/res/layout/activity_select_family.xml
  app/src/main/res/layout/activity_set_time.xml
  app/src/main/res/layout/fragment_quest_five.xml
  app/src/main/res/layout/fragment_quest_four.xml
  app/src/main/res/layout/fragment_quest_one.xml
  app/src/main/res/layout/fragment_quest_three.xml
  app/src/main/res/layout/fragment_quest_two.xml
  app/src/main/res/layout/qna_appbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
Labels: feature, chore, delete, fix, design, 서현
