Repository Team-Umbba/Umbba-Android, pull requests merged in 2024-05, with the labels that each got.

#178 [Fix/#177] 마이페이지 -> 가까워지기 조건 처리 오류 수정
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/MypageFragment.kt
Labels: fix, 서현

#179 [Fix] 기록하기 API 오류 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_app_icon-playstore.png
  app/src/main/java/com/ubcompany/umbba_android/data/repository/SettingRepositoryImpl.kt
  app/src/main/java/com/ubcompany/umbba_android/data/service/SettingService.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/DeleteRecordDialogFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/RecordActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/RecordAdapter.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/UploadRecordActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/viewmodel/DeleteRecordDialogViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/viewmodel/MypageViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/viewmodel/RecordViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/viewmodel/UploadRecordViewModel.kt
  app/src/main/res/drawable/ic_app_icon_foreground.xml
  app/src/main/res/drawable/ic_record_background.xml
  app/src/main/res/drawable/ic_umbba_logo.xml
  app/src/main/res/drawable/ic_umbba_logo_big.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_record_list.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_icon.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_icon_round.xml
  app/src/main/res/mipmap-hdpi/ic_app_icon.webp
  app/src/main/res/mipmap-hdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-mdpi/ic_app_icon.webp
  app/src/main/res/mipmap-mdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-xhdpi/ic_app_icon.webp
  app/src/main/res/mipmap-xhdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_icon.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_icon.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_icon_round.webp
  app/src/main/res/values/ic_app_icon_background.xml
  app/src/main/res/values/strings.xml
Labels: feature, chore, fix, 연진

#183 [Fix] 기록하기 API 사진 업로드 오류
  app/src/main/java/com/ubcompany/umbba_android/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/ubcompany/umbba_android/di/NetworkModule.kt
Labels: fix, 연진

#184 [Feat] 문답 새로고침 기능 추가
  app/build.gradle
  app/src/main/java/com/ubcompany/umbba_android/data/datasource/HomeRemoteDataSource.kt
  app/src/main/java/com/ubcompany/umbba_android/data/datasource/QuestionAnswerRemoteDataSource.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/request/RefreshQuestionRequestDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/IsRefreshResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/ubcompany/umbba_android/data/repository/QuestionAnswerRepositoryImpl.kt
  app/src/main/java/com/ubcompany/umbba_android/data/service/HomeService.kt
  app/src/main/java/com/ubcompany/umbba_android/data/service/QuestionAnswerService.kt
  app/src/main/java/com/ubcompany/umbba_android/domain/repository/HomeRepository.kt
  app/src/main/java/com/ubcompany/umbba_android/domain/repository/QuestionAnswerRepository.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/EndingActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/viewmodel/EndingViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/qna/RefreshQuestionDialogFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/qna/viewmodel/QuestionAnswerViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/qna/viewmodel/RefreshQuestionDialogFragmentViewModel.kt
  app/src/main/res/drawable/ic_close_umbba_black.xml
  app/src/main/res/drawable/ic_redo.xml
  app/src/main/res/drawable/shape_g400_fill_r8_rect.xml
  app/src/main/res/layout/activity_ending.xml
  app/src/main/res/layout/fragment_refresh_question_dialog.xml
  app/src/main/res/layout/qna_appbar.xml
  app/src/main/res/values/strings.xml
Labels: feature, fix, 연진
