Repository Team-Umbba/Umbba-Android, pull requests merged in 2024-04, with the labels that each got.

#171 [Feat/#165] 가까워지기 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ubcompany/umbba_android/data/datasource/CloserRemoteDataSource.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/request/CloserAnswerRequestDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/CloserAnswerResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/CloserNextResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/CloserQuestionResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/QuestionAnswerResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/repository/CloserRepositoryImpl.kt
  app/src/main/java/com/ubcompany/umbba_android/data/service/CloserService.kt
  app/src/main/java/com/ubcompany/umbba_android/di/RepositoryModule.kt
  app/src/main/java/com/ubcompany/umbba_android/di/ServiceModule.kt
  app/src/main/java/com/ubcompany/umbba_android/domain/repository/CloserRepository.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserQuestionFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserResultFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/MypageFragment.kt
  app/src/main/res/color/sel_closer_choice_chip_pri600.xml
  app/src/main/res/color/sel_closer_choice_pri600_text.xml
  app/src/main/res/layout/activity_get_close.xml
  app/src/main/res/layout/fragment_closer_check_result.xml
  app/src/main/res/layout/fragment_closer_question.xml
  app/src/main/res/values/styles.xml
Labels: feature, chore, design, 서현

#174 [Fix/#173] 튜토리얼, 가까워지기 오류 수정
  app/src/main/java/com/ubcompany/umbba_android/data/datasource/HomeRemoteDataSource.kt
  app/src/main/java/com/ubcompany/umbba_android/data/local/SharedPreferences.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/HomeFirstResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/MypageResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/repository/CloserRepositoryImpl.kt
  app/src/main/java/com/ubcompany/umbba_android/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/ubcompany/umbba_android/data/service/HomeService.kt
  app/src/main/java/com/ubcompany/umbba_android/domain/repository/HomeRepository.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserQuestionFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserResultFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/GetCloserViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/viewmodel/MypageViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/qna/ConfirmAnswerDialogFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/qna/QuestionAnswerActivity.kt
  app/src/main/res/layout/activity_get_close.xml
  app/src/main/res/layout/fragment_closer_check_result.xml
Labels: fix, refactor, 서현

#175 [Feat/#169] 기록하기 API 연결하기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ubcompany/umbba_android/data/datasource/SettingRemoteDataSource.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/request/RecordImageRequestDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/request/RecordUploadRequestDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/BaseResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/RecordImageResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/model/response/RecordListResponseDto.kt
  app/src/main/java/com/ubcompany/umbba_android/data/repository/SettingRepositoryImpl.kt
  app/src/main/java/com/ubcompany/umbba_android/data/service/SettingService.kt
  app/src/main/java/com/ubcompany/umbba_android/domain/repository/SettingRepository.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/DeleteRecordDialogFragment.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/RecordActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/RecordAdapter.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/UploadRecordActivity.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/viewmodel/RecordViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/presentation/mypage/viewmodel/UploadRecordViewModel.kt
  app/src/main/java/com/ubcompany/umbba_android/util/BitmapRequestBody.kt
  app/src/main/java/com/ubcompany/umbba_android/util/BitmapUtil.kt
  app/src/main/res/layout/activity_record.xml
  app/src/main/res/layout/item_record_list.xml
Labels: feature, fix, refactor, 연진
